// knowledge-graph/src/index.ts

export {
	buildGraphContext,
	buildIacGraphContext,
	changeHistoryForStackInstance,
	deploymentsRunningStack,
	type IacChange,
	type IacGraphExtra,
	priorChangesForDeployment,
	priorRelationshipsForServices,
	type ServiceDependency,
	type SimilarIncident,
	type StackInstanceChange,
	similarIncidents,
	stacksUsingModule,
	type TopologyEdge,
	topology,
} from "./reader.ts";
export {
	ALTER_MIGRATIONS,
	type ConfigChangeNode,
	ConfigChangeNodeSchema,
	type DeploymentNode,
	DeploymentNodeSchema,
	EMBEDDING_DIM,
	type FindingNode,
	type IncidentNode,
	MIGRATIONS,
	type ModuleNode,
	ModuleNodeSchema,
	NODE_LABELS,
	type NodeLabel,
	type PipelineNode,
	PipelineNodeSchema,
	REL_TYPES,
	type RelType,
	type ServiceNode,
	type SessionNode,
	SessionNodeSchema,
	type StackInstanceNode,
	StackInstanceNodeSchema,
	type StackNode,
	StackNodeSchema,
	VECTOR_INDEX_SETUP,
	type WorkflowNode,
	WorkflowNodeSchema,
} from "./schema.ts";
export {
	_setGraphStoreForTesting,
	type GraphRow,
	type GraphStore,
	getGraphStore,
	graphPath,
	InMemoryGraphStore,
	isKnowledgeGraphEnabled,
	LadybugStore,
} from "./store.ts";
export {
	type ChangeOutcome,
	type CorrelationLink,
	type DeploymentSeed,
	type EntityGraph,
	type IacChangeRecord,
	type IncidentRecord,
	linkCorrelation,
	linkResolution,
	linkStackModule,
	type PipelineRecord,
	recordIacChange,
	recordIncident,
	recordPipeline,
	seedDeployments,
	seedModules,
	seedStackInstances,
	seedStacks,
	setChangeOutcome,
	upsertEntities,
} from "./writer.ts";
