// src/config/envMapping.ts

export const envVarMapping = {
	server: {
		name: "MCP_SERVER_NAME",
		version: "MCP_SERVER_VERSION",
		readOnlyMode: "READ_ONLY_MODE",
		readOnlyStrictMode: "READ_ONLY_STRICT_MODE",
		maxQueryTimeout: "MCP_MAX_QUERY_TIMEOUT",
		maxResultsPerQuery: "MCP_MAX_RESULTS_PER_QUERY",
		transportMode: "MCP_TRANSPORT",
		port: "MCP_PORT",
		host: "MCP_HOST",
		path: "MCP_PATH",
		sessionMode: "MCP_SESSION_MODE",
		idleTimeout: "MCP_IDLE_TIMEOUT",
		apiKey: "MCP_API_KEY",
		allowedOrigins: "MCP_ALLOWED_ORIGINS",
		maxResponseSizeBytes: "MCP_MAX_RESPONSE_SIZE_BYTES",
		defaultPageSize: "MCP_DEFAULT_PAGE_SIZE",
		maxPageSize: "MCP_MAX_PAGE_SIZE",
		enableResponseCompression: "MCP_ENABLE_RESPONSE_COMPRESSION",
		autoSummarizeLargeResponses: "MCP_AUTO_SUMMARIZE_LARGE_RESPONSES",
		monitoringPort: "MONITORING_PORT",
	},
	elasticsearch: {
		url: "ES_URL",
		apiKey: "ES_API_KEY",
		username: "ES_USERNAME",
		password: "ES_PASSWORD",
		caCert: "ES_CA_CERT",
		maxRetries: "ES_MAX_RETRIES",
		requestTimeout: "ES_REQUEST_TIMEOUT",
		compression: "ES_COMPRESSION",
		enableMetaHeader: "ES_ENABLE_META_HEADER",
		disablePrototypePoisoningProtection: "ES_DISABLE_PROTOTYPE_POISONING_PROTECTION",
	},
	logging: {
		level: "LOG_LEVEL",
		format: "LOG_FORMAT",
		includeMetadata: "LOG_INCLUDE_METADATA",
	},
	security: {
		allowDestructiveOperations: "ALLOW_DESTRUCTIVE_OPERATIONS",
		allowSchemaModifications: "ALLOW_SCHEMA_MODIFICATIONS",
		allowIndexManagement: "ALLOW_INDEX_MANAGEMENT",
		maxBulkOperations: "MAX_BULK_OPERATIONS",
	},
	langsmith: {
		tracing: "LANGSMITH_TRACING",
		endpoint: "LANGSMITH_ENDPOINT",
		apiKey: "LANGSMITH_API_KEY",
		project: "ELASTIC_LANGSMITH_PROJECT",
		projectFallback: "LANGSMITH_PROJECT",
	},
	sessionTracking: {
		enabled: "SESSION_TRACKING_ENABLED",
		sessionTimeoutMinutes: "SESSION_TIMEOUT_MINUTES",
		includeSessionInTraceName: "SESSION_ID_IN_TRACE_NAME",
		maxConcurrentSessions: "MAX_CONCURRENT_SESSIONS",
		conversationDetectionThresholdSeconds: "CONVERSATION_DETECTION_THRESHOLD_SECONDS",
	},
} as const;
