// deploy/accounts/eu-b2becom-v2-prd/main.tf
//
// GENERATED by `just fleet render` from deploy/fleet.yaml (SIO-1653). Do not
// edit by hand; change the manifest or scripts/fleet/render.ts and re-render.
// Identifiers (subnets, CIDRs, hub IP, token) come from terraform.tfvars,
// which is gitignored and written by the same command.
terraform {
  required_version = ">= 1.10.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.60"
    }
  }
}

provider "aws" {
  region  = var.region
  profile = var.aws_profile

  default_tags {
    tags = {
      Project     = "pi-coms-net"
      ManagedBy   = "terraform"
      Stack       = "b2becom-v2-prd"
      Environment = "prd"
      // The coms-net project namespace these agents register into. Informational:
      // routing is by hub (per environment) and the tunnel is selected by AWS
      // profile, so nothing filters on this tag. It exists so an operator reading
      // the console can tell which registry an instance belongs to without
      // cross-referencing the manifest. NOT the same thing as the Project tag
      // above, which is the Terraform stack marker.
      ComsProject = "pi-coms-prd"
    }
  }
}

variable "region" {
  description = "AWS region."
  type        = string
  default     = "eu-central-1"
}

variable "aws_profile" {
  description = "Local AWS CLI profile for this account."
  type        = string
  default     = "eu-b2becom-v2-prd"
}

variable "coms_auth_token" {
  description = "This spoke's hub token (minted by just fleet tokens ensure; terraform.tfvars)."
  type        = string
  sensitive   = true
}

variable "hub_url" {
  description = "Private URL of the prd hub, reached over the Transit Gateway (terraform.tfvars)."
  type        = string
}

variable "agent_subnet_id" {
  description = "Private subnet for the agent host (terraform.tfvars)."
  type        = string
}

variable "dist_bucket" {
  description = "Fleet distribution bucket of the prd hub account (terraform.tfvars)."
  type        = string
}

variable "pi_model" {
  description = "Bedrock inference-profile id the agent runs."
  type        = string
  default     = "eu.anthropic.claude-haiku-4-5-20251001-v1:0"
}

variable "agent_name" {
  description = "coms-net name for this account's agent; the monitor pairs as monitor-<agent_name>."
  type        = string
  default     = "eu-b2becom-v2-prd"
}

variable "readonly_external_id" {
  description = "ExternalId gating DevOpsAgentReadOnly (the analyzer's, adopted)."
  type        = string
  default     = "devops-agent-prod-access"
}

variable "repo_url" {
  description = "Unused in bundle mode; kept for the module contract."
  type        = string
  default     = "unused-bundle-mode"
}

// Adopt mode: this account already carries DevOpsAgentReadOnly for the incident
// analyzer. The role is imported into state and its trust policy gains one
// statement for the local instance role; the analyzer's statement and the
// attached analyzer policies are never touched (see modules/agent).
import {
  to = module.agent.aws_iam_role.devops_readonly[0]
  id = "DevOpsAgentReadOnly"
}

module "agent" {
  source = "../../modules/agent"

  hub_url              = var.hub_url
  coms_auth_token      = var.coms_auth_token
  repo_url             = var.repo_url
  agent_name           = var.agent_name
  coms_project         = "pi-coms-prd"
  subnet_id            = var.agent_subnet_id
  associate_public_ip  = false
  instance_type        = "t4g.small"
  pi_model             = var.pi_model
  pi_provider          = "amazon-bedrock"
  enable_bedrock       = true
  readonly_role        = true
  readonly_role_mode   = "adopt"
  readonly_external_id = var.readonly_external_id
  bundle_s3_uri        = "s3://${var.dist_bucket}/fleet"
  dist_bucket_arn      = "arn:aws:s3:::${var.dist_bucket}"
}

// Every 30 minutes each tagged host compares its bundle version against S3 and
// re-bootstraps on change; `just fleet rollout` triggers the same command now.
resource "aws_ssm_association" "fleet_update" {
  name             = "AWS-RunShellScript"
  association_name = "pi-coms-fleet-update"

  targets {
    key    = "tag:Project"
    values = ["pi-coms-net"]
  }

  schedule_expression = "rate(30 minutes)"

  parameters = {
    commands = "[ -x /usr/local/bin/pi-coms-update ] && /usr/local/bin/pi-coms-update || true"
  }
}

output "agent_name" {
  value = module.agent.agent_name
}

output "agent_instance_id" {
  value = module.agent.agent_instance_id
}

output "devops_readonly_role_arn" {
  value = module.agent.devops_readonly_role_arn
}

output "provider_keys_parameter_name" {
  value = module.agent.provider_keys_parameter_name
}

output "attach_to_agent" {
  value = module.agent.attach_to_agent
}
