// deploy/accounts/eu-mendix-platform-prd/backend.tf (generated by just fleet render, SIO-1653)
// Bucket, region and profile come from backend.hcl (gitignored, same command):
//   terraform init -backend-config=backend.hcl
// The state bucket is created once per hub by `just fleet backend-init <hub>`.
terraform {
  backend "s3" {
    key          = "accounts/eu-mendix-platform-prd.tfstate"
    use_lockfile = true
    encrypt      = true
  }
}
