// packages/agent/src/aws-policy-actions.ts
// SIO-1120: the set of AWS IAM actions the DevOpsAgentReadOnly role is granted, derived from the
// two committed policy documents under scripts/agentcore/policies/:
//   - devops-agent-readonly-policy.json               (base read)
//   - devops-agent-readonly-troubleshooting-policy.json (network-path + change diagnosis)
//
// The aggregator grounding guard (detectUngroundedBlockers) uses this to catch the exact bug from
// the 2026-07-15 localcore incident: the LLM claimed a GRANTED action (ec2:DescribeRouteTables) was
// "not permitted". If a Gaps/Recommendations bullet names an action in this set and NO auth error
// for that action was actually observed, the claim is fabricated.
//
// This is a frozen literal, NOT parsed from disk at runtime -- packages/agent runs under Vite SSR
// in the web app and the policy JSON lives outside the bundle. aws-policy-actions.test.ts reads both
// JSON files and asserts this set stays in parity, so drift fails CI rather than silently rotting.

// All actions are stored lowercased for case-insensitive matching against LLM-emitted text.
const GRANTED_ACTIONS: ReadonlySet<string> = new Set(
	[
		// Base policy (devops-agent-readonly-policy.json): core read surface.
		"sts:getcalleridentity",
		"ec2:describeregions",
		"ec2:describeavailabilityzones",
		"ec2:describevpcs",
		"ec2:describesubnets",
		"ec2:describeroutetables",
		"ec2:describesecuritygroups",
		"ec2:describenetworkinterfaces",
		"ec2:describevpcendpoints",
		"ec2:describeaddresses",
		"elasticloadbalancing:describeloadbalancers",
		"elasticloadbalancing:describelisteners",
		"elasticloadbalancing:describetargetgroups",
		"elasticloadbalancing:describetargethealth",
		"ec2:describeinstances",
		"ec2:describeinstancestatus",
		"ec2:describelaunchtemplates",
		"ec2:describeimages",
		"autoscaling:describeautoscalinggroups",
		"autoscaling:describeautoscalinginstances",
		"ecs:listclusters",
		"ecs:describeclusters",
		"ecs:listservices",
		"ecs:describeservices",
		"ecs:listtasks",
		"ecs:describetasks",
		"ecs:describetaskdefinition",
		"ecs:listcontainerinstances",
		"ecs:describecontainerinstances",
		"eks:listclusters",
		"eks:describecluster",
		"lambda:listfunctions",
		"lambda:getfunctionconfiguration",
		"lambda:listeventsourcemappings",
		"rds:describedbinstances",
		"rds:describedbclusters",
		"dynamodb:listtables",
		"dynamodb:describetable",
		"elasticache:describecacheclusters",
		"elasticache:describereplicationgroups",
		"s3:listallmybuckets",
		"s3:getbucketlocation",
		"s3:getbucketversioning",
		"s3:getbucketencryption",
		"s3:getbucketpublicaccessblock",
		"s3:getbuckettagging",
		"s3:getbucketpolicystatus",
		"sns:listtopics",
		"sns:gettopicattributes",
		"sqs:listqueues",
		"sqs:getqueueattributes",
		"events:listeventbuses",
		"events:listrules",
		"events:describerule",
		"events:listtargetsbyrule",
		"states:liststatemachines",
		"states:describestatemachine",
		"cloudwatch:listmetrics",
		"cloudwatch:getmetricdata",
		"cloudwatch:getmetricstatistics",
		"cloudwatch:describealarms",
		"cloudwatch:describealarmsformetric",
		"cloudwatch:getdashboard",
		"cloudwatch:listdashboards",
		"logs:describeloggroups",
		"logs:describelogstreams",
		"logs:getlogevents",
		"logs:filterlogevents",
		"logs:startquery",
		"logs:getqueryresults",
		"logs:stopquery",
		"xray:getservicegraph",
		"xray:gettracesummaries",
		"xray:batchgettraces",
		"xray:getgroups",
		"health:describeevents",
		"health:describeeventdetails",
		"config:describeconfigrules",
		"config:describecompliancebyconfigrule",
		"config:listdiscoveredresources",
		"config:getdiscoveredresourcecounts",
		"cloudformation:liststacks",
		"cloudformation:describestacks",
		"cloudformation:describestackevents",
		"cloudformation:gettemplate",
		"cloudformation:liststackresources",
		"tag:getresources",
		"tag:gettagkeys",
		"tag:gettagvalues",
		"cloudtrail:describetrails",
		"cloudtrail:gettrailstatus",
		"cloudtrail:listtrails",
		"securityhub:getfindings",
		"securityhub:describehub",
		"securityhub:getenabledstandards",
		"guardduty:listdetectors",
		"guardduty:getdetector",
		"guardduty:listfindings",
		"guardduty:getfindings",
		// Troubleshooting policy (devops-agent-readonly-troubleshooting-policy.json): network-path + change diagnosis.
		"ec2:describevpcendpointservices",
		"ec2:describevpcendpointconnections",
		"ec2:describevpcendpointserviceconfigurations",
		"ec2:describenatgateways",
		"ec2:describeinternetgateways",
		"ec2:describeegressonlyinternetgateways",
		"ec2:describenetworkacls",
		"ec2:describevpcpeeringconnections",
		"ec2:describevpcattribute",
		"ec2:describesecuritygrouprules",
		"ec2:describedhcpoptions",
		"ec2:describeprefixlists",
		"ec2:describemanagedprefixlists",
		"ec2:getmanagedprefixlistentries",
		"ec2:describeflowlogs",
		"ec2:describetransitgateways",
		"ec2:describetransitgatewayattachments",
		"ec2:describetransitgatewayvpcattachments",
		"ec2:describetransitgatewayroutetables",
		"ec2:searchtransitgatewayroutes",
		"ec2:describenetworkinsightspaths",
		"ec2:describenetworkinsightsanalyses",
		"ec2:describevpnconnections",
		"ec2:describevpngateways",
		"ec2:describecustomergateways",
		"ec2:describeclientvpnendpoints",
		"elasticloadbalancing:describeloadbalancerattributes",
		"elasticloadbalancing:describetargetgroupattributes",
		"elasticloadbalancing:describerules",
		"elasticloadbalancing:describetags",
		"elasticloadbalancing:describesslpolicies",
		"network-firewall:describefirewall",
		"network-firewall:describefirewallpolicy",
		"network-firewall:describeloggingconfiguration",
		"network-firewall:listfirewalls",
		"directconnect:describeconnections",
		"directconnect:describevirtualinterfaces",
		"route53:listhostedzones",
		"route53:gethostedzone",
		"route53:listresourcerecordsets",
		"route53:listhealthchecks",
		"route53:gethealthcheckstatus",
		"route53resolver:listresolverendpoints",
		"route53resolver:listresolverrules",
		"route53resolver:listresolverruleassociations",
		"route53resolver:listresolverquerylogconfigs",
		"kafka:listclustersv2",
		"kafka:describeclusterv2",
		"kafka:getbootstrapbrokers",
		"kafka:listnodes",
		"kafka:describeconfiguration",
		"kafka:listclientvpcconnections",
		"kafka:listclusteroperationsv2",
		"sts:decodeauthorizationmessage",
		"kms:describekey",
		"kms:listaliases",
		"kms:getkeypolicy",
		"kms:getkeyrotationstatus",
		"config:getresourceconfighistory",
		"config:batchgetresourceconfig",
		"config:selectresourceconfig",
		"config:describeconfigurationrecorderstatus",
		"cloudtrail:lookupevents",
		"cloudtrail:geteventselectors",
		"autoscaling:describescalingactivities",
		"autoscaling:describepolicies",
		"application-autoscaling:describescalabletargets",
		"application-autoscaling:describescalingpolicies",
		"application-autoscaling:describescalingactivities",
		"ecs:listtaskdefinitions",
		"ecs:listtaskdefinitionfamilies",
		"ecs:describecapacityproviders",
		"ecr:describerepositories",
		"ecr:describeimages",
		"ecr:listimages",
		"ecr:getrepositorypolicy",
		"ecr:getlifecyclepolicy",
		"cloudformation:describestackresourcedrifts",
		"cloudformation:describestackresource",
		"cloudformation:listexports",
		"cloudformation:listimports",
		"cloudformation:describechangeset",
		"cloudformation:listchangesets",
		"servicequotas:listservicequotas",
		"servicequotas:getservicequota",
		"lambda:getfunction",
		"lambda:getpolicy",
		"lambda:getaccountsettings",
		"states:describeexecution",
		"states:listexecutions",
		"states:getexecutionhistory",
		"rds:describeevents",
		"elasticache:describeevents",
		"health:describeaffectedentities",
		"health:describeeventaggregates",
		"logs:describemetricfilters",
		"logs:describesubscriptionfilters",
		"logs:getloggroupfields",
		"ssm:describeparameters",
		"secretsmanager:listsecrets",
		"secretsmanager:describesecret",
	].map((a) => a.toLowerCase()),
);

// Matches an IAM action token `service:Action` in free text. Service names use lowercase +
// hyphen (network-firewall, application-autoscaling); the action is alphanumeric.
const ACTION_TOKEN_RE = /\b([a-z0-9-]+:[A-Za-z][A-Za-z0-9]+)\b/g;

/** True when the action (case-insensitive) is granted by either committed policy. */
export function isGrantedAction(action: string): boolean {
	return GRANTED_ACTIONS.has(action.toLowerCase());
}

/** Extract every `service:Action` token from a line, lowercased. Empty when none present. */
export function extractIamActions(text: string): string[] {
	const out: string[] = [];
	for (const m of text.matchAll(ACTION_TOKEN_RE)) {
		const token = m[1];
		if (token) out.push(token.toLowerCase());
	}
	return out;
}

/** Exposed for the parity test. */
export function _grantedActionsForTest(): ReadonlySet<string> {
	return GRANTED_ACTIONS;
}
