// scripts/fleet/render.ts
// SIO-1653: render one Terraform root per spoke from the manifest. The committed
// main.tf and backend.tf carry no identifiers; subnets, CIDRs, the hub IP and the
// token live in terraform.tfvars (gitignored), which `render` writes and
// `tokens ensure` updates.
import {
	DEFAULT_AUTH_PATH,
	DEFAULT_HUB_PORT,
	externalIdFor,
	type FleetManifest,
	hubFor,
	spokeFor,
} from "./manifest.ts";

export type RenderedRoot = {
	"main.tf": string;
	"backend.tf": string;
	"backend.hcl": string;
	"terraform.tfvars": string;
};

export const GENERATED_HEADER = (name: string) =>
	`// deploy/accounts/${name}/main.tf
//
// GENERATED by \`just fleet render\` from deploy/fleet.yaml (SIO-1653). Do not
// edit by hand; change the manifest or scripts/fleet/render.ts and re-render.
// Identifiers (subnets, CIDRs, hub IP, token) come from terraform.tfvars,
// which is gitignored and written by the same command.
`;

const TOKEN_PLACEHOLDER = "<set by: just fleet tokens ensure>";

function hcl(value: string): string {
	return JSON.stringify(value);
}

export function renderMainTf(manifest: FleetManifest, name: string): string {
	const spoke = spokeFor(manifest, name);
	const hub = hubFor(manifest, spoke.hub);
	const stack = name.replace(/^eu-/, "");
	const mode = spoke.readonly_role;
	const hostsHub = spoke.hosts_hub === true;
	const parts: string[] = [GENERATED_HEADER(name)];

	parts.push(`terraform {
  required_version = ">= 1.10.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.60"
    }
  }
}

provider "aws" {
  region  = var.region
  profile = var.aws_profile

  default_tags {
    tags = {
      Project     = "pi-coms-net"
      ManagedBy   = "terraform"
      Stack       = ${hcl(stack)}
      Environment = ${hcl(spoke.env)}
      // The coms-net project namespace these agents register into. Informational:
      // routing is by hub (per environment) and the tunnel is selected by AWS
      // profile, so nothing filters on this tag. It exists so an operator reading
      // the console can tell which registry an instance belongs to without
      // cross-referencing the manifest. NOT the same thing as the Project tag
      // above, which is the Terraform stack marker.
      ComsProject = ${hcl(hub.project ?? "default")}
    }
  }
}

variable "region" {
  description = "AWS region."
  type        = string
  default     = ${hcl(manifest.defaults.region)}
}

variable "aws_profile" {
  description = "Local AWS CLI profile for this account."
  type        = string
  default     = ${hcl(spoke.profile)}
}

variable "coms_auth_token" {
  description = "This spoke's hub token (minted by just fleet tokens ensure; terraform.tfvars)."
  type        = string
  sensitive   = true
}

variable "hub_url" {
  description = "Private URL of the ${spoke.env} hub, reached over the Transit Gateway (terraform.tfvars)."
  type        = string
}

variable "agent_subnet_id" {
  description = "Private subnet for the agent host (terraform.tfvars)."
  type        = string
}

variable "dist_bucket" {
  description = "Fleet distribution bucket of the ${spoke.env} hub account (terraform.tfvars)."
  type        = string
}

variable "pi_model" {
  description = "Bedrock inference-profile id the agent runs."
  type        = string
  default     = ${hcl(spoke.pi_model ?? manifest.defaults.pi_model)}
}

variable "agent_name" {
  description = "coms-net name for this account's agent; the monitor pairs as monitor-<agent_name>."
  type        = string
  default     = ${hcl(spoke.agent_name ?? name)}
}

variable "readonly_external_id" {
  description = "ExternalId gating DevOpsAgentReadOnly (${mode === "adopt" ? "the analyzer's, adopted" : "created here"})."
  type        = string
  default     = ${hcl(mode === "none" ? "" : externalIdFor(manifest, name))}
}

variable "repo_url" {
  description = "Unused in bundle mode; kept for the module contract."
  type        = string
  default     = "unused-bundle-mode"
}
`);

	if (hostsHub) {
		parts.push(`
variable "hub_subnet_id" {
  description = "Private subnet for the hub host (terraform.tfvars)."
  type        = string
}

variable "hub_private_ip" {
  description = "Pinned private IP of the hub; spokes and operator configs reference it (terraform.tfvars)."
  type        = string
}

variable "allowed_cidrs" {
  description = "CIDRs allowed to reach the hub port: this environment's spoke VPCs and operator ranges only (terraform.tfvars)."
  type        = list(string)
}

variable "org_id" {
  description = "AWS Organizations id (o-...) scoping distribution-bucket reads (terraform.tfvars)."
  type        = string
}

// Fleet distribution bucket for the ${spoke.env} environment.
data "aws_caller_identity" "current" {}

resource "aws_s3_bucket" "dist" {
  bucket = "pi-coms-dist-\${data.aws_caller_identity.current.account_id}"
}

resource "aws_s3_bucket_versioning" "dist" {
  bucket = aws_s3_bucket.dist.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_public_access_block" "dist" {
  bucket                  = aws_s3_bucket.dist.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_policy" "dist_org_read" {
  bucket = aws_s3_bucket.dist.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "OrgRead"
      Effect    = "Allow"
      Principal = "*"
      Action    = ["s3:GetObject", "s3:ListBucket"]
      Resource  = [aws_s3_bucket.dist.arn, "\${aws_s3_bucket.dist.arn}/*"]
      Condition = { StringEquals = { "aws:PrincipalOrgID" = var.org_id } }
    }]
  })
}

// The ${spoke.env} hub. Directory mode: per-principal tokens under ${hub.auth_path ?? DEFAULT_AUTH_PATH};
// fleet tokens ensure mints one per spoke here.
module "hub" {
  source = "../../modules/hub"

  coms_auth_token = var.coms_auth_token
  subnet_id       = var.hub_subnet_id
  private_ip      = var.hub_private_ip
  allowed_cidrs   = var.allowed_cidrs
  repo_url        = var.repo_url
  bundle_s3_uri   = "s3://\${aws_s3_bucket.dist.bucket}/fleet"
  dist_bucket_arn = aws_s3_bucket.dist.arn
  auth_ssm_path   = ${hcl(hub.auth_path ?? DEFAULT_AUTH_PATH)}
  port            = ${hub.port ?? DEFAULT_HUB_PORT}
}
`);
	}

	if (mode === "adopt") {
		parts.push(`
// Adopt mode: this account already carries DevOpsAgentReadOnly for the incident
// analyzer. The role is imported into state and its trust policy gains one
// statement for the local instance role; the analyzer's statement and the
// attached analyzer policies are never touched (see modules/agent).
import {
  to = module.agent.aws_iam_role.devops_readonly[0]
  id = "DevOpsAgentReadOnly"
}
`);
	}

	// biome-ignore lint/suspicious/noTemplateCurlyInString: SIO-1653 - HCL interpolation, not a JS template
	const bundleUri = hostsHub ? '"s3://${aws_s3_bucket.dist.bucket}/fleet"' : '"s3://${var.dist_bucket}/fleet"';
	// biome-ignore lint/suspicious/noTemplateCurlyInString: SIO-1653 - HCL interpolation, not a JS template
	const bucketArn = hostsHub ? "aws_s3_bucket.dist.arn" : '"arn:aws:s3:::${var.dist_bucket}"';
	parts.push(`
module "agent" {
  source = "../../modules/agent"

  hub_url              = ${hostsHub ? "module.hub.hub_url" : "var.hub_url"}
  coms_auth_token      = var.coms_auth_token
  repo_url             = var.repo_url
  agent_name           = var.agent_name
  coms_project         = ${hcl(hub.project ?? "default")}
  subnet_id            = var.agent_subnet_id
  associate_public_ip  = false
  instance_type        = ${hcl(spoke.instance_type ?? manifest.defaults.instance_type)}
  pi_model             = var.pi_model
  pi_provider          = "amazon-bedrock"
  enable_bedrock       = true
  readonly_role        = ${mode === "none" ? "false" : "true"}
  readonly_role_mode   = ${hcl(mode)}
  readonly_external_id = var.readonly_external_id
  bundle_s3_uri        = ${bundleUri}
  dist_bucket_arn      = ${bucketArn}
}

// Every 30 minutes each tagged host compares its bundle version against S3 and
// re-bootstraps on change; \`just fleet rollout\` triggers the same command now.
resource "aws_ssm_association" "fleet_update" {
  name             = "AWS-RunShellScript"
  association_name = "pi-coms-fleet-update"

  targets {
    key    = "tag:Project"
    values = ["pi-coms-net"]
  }

  schedule_expression = "rate(30 minutes)"

  parameters = {
    commands = "[ -x /usr/local/bin/pi-coms-update ] && /usr/local/bin/pi-coms-update || true"
  }
}

output "agent_name" {
  value = module.agent.agent_name
}

output "agent_instance_id" {
  value = module.agent.agent_instance_id
}

output "devops_readonly_role_arn" {
  value = module.agent.devops_readonly_role_arn
}

output "provider_keys_parameter_name" {
  value = module.agent.provider_keys_parameter_name
}

output "attach_to_agent" {
  value = module.agent.attach_to_agent
}
`);

	if (hostsHub) {
		parts.push(`
output "hub_url" {
  value = module.hub.hub_url
}

output "hub_instance_id" {
  value = module.hub.hub_instance_id
}

output "dist_bucket" {
  value = aws_s3_bucket.dist.bucket
}

output "attach_to_hub" {
  value = module.hub.attach_to_hub
}
`);
	}
	return parts.join("");
}

// SIO-1666: keyed by HUB, not environment -- the state bucket lives in the hub's
// account, and two hubs in one environment have two different accounts.
export function stateBucketName(manifest: FleetManifest, hubKey: string): string {
	const hub = hubFor(manifest, hubKey);
	return `pi-coms-tfstate-${hub.account_id ?? "<hub-account-id>"}`;
}

// State lives in the environment's hub account, addressed with the hub's local
// profile, so spoke state never needs a cross-account bucket policy. The bucket
// name carries the hub account id, so it stays out of the committed backend.tf:
// bucket, region and profile go to backend.hcl (gitignored), passed at init.
export function renderBackendTf(manifest: FleetManifest, name: string): string {
	spokeFor(manifest, name);
	return `// deploy/accounts/${name}/backend.tf (generated by just fleet render, SIO-1653)
// Bucket, region and profile come from backend.hcl (gitignored, same command):
//   terraform init -backend-config=backend.hcl
// The state bucket is created once per hub by \`just fleet backend-init <hub>\`.
terraform {
  backend "s3" {
    key          = ${hcl(`accounts/${name}.tfstate`)}
    use_lockfile = true
    encrypt      = true
  }
}
`;
}

export function renderBackendHcl(manifest: FleetManifest, name: string): string {
	const spoke = spokeFor(manifest, name);
	const hub = hubFor(manifest, spoke.hub);
	return `# deploy/accounts/${name}/backend.hcl -- generated by just fleet render (gitignored)
bucket  = ${hcl(stateBucketName(manifest, spoke.hub))}
region  = ${hcl(hub.region)}
profile = ${hcl(hub.profile)}
`;
}

// Preserves an existing coms_auth_token line so re-rendering never drops a
// minted token; everything else is regenerated from the manifest.
export function renderTfvars(manifest: FleetManifest, name: string, existing?: string): string {
	const spoke = spokeFor(manifest, name);
	const hub = hubFor(manifest, spoke.hub);
	const tokenLine = existing?.split("\n").find((l) => l.startsWith("coms_auth_token"));
	const lines = [
		`# deploy/accounts/${name}/terraform.tfvars -- generated by just fleet render (gitignored)`,
		tokenLine ?? `coms_auth_token = ${hcl(TOKEN_PLACEHOLDER)}`,
		`hub_url         = ${hcl(hub.url)}`,
		`agent_subnet_id = ${hcl(spoke.subnet_id)}`,
		`dist_bucket     = ${hcl(hub.dist_bucket ?? `pi-coms-dist-${hub.account_id ?? "<hub-account-id>"}`)}`,
	];
	if (spoke.hosts_hub) {
		lines.push(
			`hub_subnet_id   = ${hcl(hub.subnet_id)}`,
			`hub_private_ip  = ${hcl(hub.private_ip)}`,
			`allowed_cidrs   = ${JSON.stringify(hub.allowed_cidrs)}`,
			`org_id          = ${hcl(manifest.org_id ?? "<set: aws organizations describe-organization>")}`,
		);
	}
	return `${lines.join("\n")}\n`;
}

export function renderRoot(manifest: FleetManifest, name: string, existingTfvars?: string): RenderedRoot {
	return {
		"main.tf": renderMainTf(manifest, name),
		"backend.tf": renderBackendTf(manifest, name),
		"backend.hcl": renderBackendHcl(manifest, name),
		"terraform.tfvars": renderTfvars(manifest, name, existingTfvars),
	};
}

export function hasToken(tfvars: string): boolean {
	const line = tfvars.split("\n").find((l) => l.startsWith("coms_auth_token"));
	return line !== undefined && !line.includes(TOKEN_PLACEHOLDER);
}

export function withToken(tfvars: string, token: string): string {
	const lines = tfvars.split("\n");
	const idx = lines.findIndex((l) => l.startsWith("coms_auth_token"));
	const line = `coms_auth_token = ${hcl(token)}`;
	if (idx >= 0) lines[idx] = line;
	else lines.splice(1, 0, line);
	return lines.join("\n");
}
