// deploy/accounts/eu-shared-services-prd/main.tf
//
// GENERATED by `just fleet render` from deploy/fleet.yaml (SIO-1653). Do not
// edit by hand; change the manifest or scripts/fleet/render.ts and re-render.
// Identifiers (subnets, CIDRs, hub IP, token) come from terraform.tfvars,
// which is gitignored and written by the same command.
terraform {
  required_version = ">= 1.10.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.60"
    }
  }
}

provider "aws" {
  region  = var.region
  profile = var.aws_profile

  default_tags {
    // SIO-1759: the organization's required tags (values in terraform.tfvars),
    // merged UNDER the pi-coms stack markers so a marker always wins. The
    // provider carries them to the instance and every other taggable resource
    // here; the agent module copies them onto the root volume and primary ENI,
    // which default_tags does not keep current.
    tags = merge(var.org_tags, {
      Project     = "pi-coms-net"
      ManagedBy   = "terraform"
      Stack       = "shared-services-prd"
      Environment = "prd"
      // The coms-net project namespace these agents register into. Informational:
      // routing is by hub (per environment) and the tunnel is selected by AWS
      // profile, so nothing filters on this tag. It exists so an operator reading
      // the console can tell which registry an instance belongs to without
      // cross-referencing the manifest. NOT the same thing as the Project tag
      // above, which is the Terraform stack marker.
      ComsProject = "pi-coms-prd"
    })
  }
}

variable "region" {
  description = "AWS region."
  type        = string
  default     = "eu-central-1"
}

variable "aws_profile" {
  description = "Local AWS CLI profile for this account."
  type        = string
  default     = "eu-shared-services-prd"
}

variable "coms_auth_token" {
  description = "This spoke's hub token (minted by just fleet tokens ensure; terraform.tfvars)."
  type        = string
  sensitive   = true
}

variable "hub_url" {
  description = "Private URL of the prd hub, reached over the Transit Gateway (terraform.tfvars)."
  type        = string
}

variable "agent_subnet_id" {
  description = "Private subnet for the agent host (terraform.tfvars)."
  type        = string
}

variable "dist_bucket" {
  description = "Fleet distribution bucket of the prd hub account (terraform.tfvars)."
  type        = string
}

// SIO-1821: the hub account's report topic, which lives in another account.
// Cross-account, so it is a value in terraform.tfvars rather than a reference --
// the same shape as dist_bucket above. Read it from the hub root's
// monitor_report_sns_topic_arn output.
variable "monitor_report_sns_topic_arn" {
  description = "SNS topic in the prd hub account that monitor reports are mailed to (terraform.tfvars)."
  type        = string
  default     = ""
}

variable "org_tags" {
  description = "Organization-required tags applied to every resource (terraform.tfvars)."
  type        = map(string)
  default     = {}
}

variable "pi_model" {
  description = "Bedrock inference-profile id the agent runs."
  type        = string
  default     = "eu.anthropic.claude-sonnet-5"
}

variable "agent_name" {
  description = "coms-net name for this account's agent; the monitor pairs as monitor-<agent_name>."
  type        = string
  default     = "eu-shared-services-prd"
}

variable "readonly_external_id" {
  description = "ExternalId gating DevOpsAgentReadOnly (the analyzer's, adopted)."
  type        = string
  default     = "devops-agent-prod-access"
}

variable "repo_url" {
  description = "Unused in bundle mode; kept for the module contract."
  type        = string
  default     = "unused-bundle-mode"
}

variable "hub_subnet_id" {
  description = "Private subnet for the hub host (terraform.tfvars)."
  type        = string
}

variable "hub_private_ip" {
  description = "Pinned private IP of the hub; spokes and operator configs reference it (terraform.tfvars)."
  type        = string
}

variable "allowed_cidrs" {
  description = "CIDRs allowed to reach the hub port: this environment's spoke VPCs and operator ranges only (terraform.tfvars)."
  type        = list(string)
}

variable "org_id" {
  description = "AWS Organizations id (o-...) scoping distribution-bucket reads (terraform.tfvars)."
  type        = string
}

// Fleet distribution bucket for the prd environment.
data "aws_caller_identity" "current" {}

resource "aws_s3_bucket" "dist" {
  bucket = "pi-coms-dist-${data.aws_caller_identity.current.account_id}"
}

resource "aws_s3_bucket_versioning" "dist" {
  bucket = aws_s3_bucket.dist.id
  versioning_configuration {
    status = "Enabled"
  }
}

resource "aws_s3_bucket_public_access_block" "dist" {
  bucket                  = aws_s3_bucket.dist.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

// SIO-1821: the topic every monitor in this environment mails its daily digest
// and weekly suppression review to. Project-owned on purpose -- the estate
// already carries SNS topics belonging to other teams, and their default
// policies would accept a publish from any principal in the account. Publishing
// fleet digests there would put operational detail about these accounts into a
// channel someone else is on call for.
//
// The org's required tags arrive through the provider's default_tags, so this
// topic is born compliant with the required-tags Config rule.
//
// No retention is set because the attribute does not exist on a standard topic:
// SNS is a fan-out bus, and the 14-day guarantee lives on the hub mailbox via
// REPORT_TTL_MS. The email copy is strictly best-effort.
resource "aws_sns_topic" "monitor_reports" {
  name = "pi-coms-monitor-reports"
}

// Only the spoke roles of this environment may publish. The SNS default policy
// allows any principal in the account, which is exactly the looseness that made
// the other teams' topics publishable by us -- not a property worth inheriting.
resource "aws_sns_topic_policy" "monitor_reports" {
  arn = aws_sns_topic.monitor_reports.arn

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Sid       = "SpokeMonitorsPublish"
      Effect    = "Allow"
      Principal = "*"
      Action    = "sns:Publish"
      Resource  = aws_sns_topic.monitor_reports.arn
      // Scoped by CONDITION rather than by a principal list, for the same reason
      // the dist bucket above is: no spoke carries an account_id in the manifest
      // (only hubs do), so a rendered list of full role ARNs would be empty or
      // wrong. An empty Principal.AWS = [] grants NOBODY and the monitor
      // swallows the resulting 403, so the feature would look enabled and
      // deliver no email at all.
      //
      // Both conditions must hold: inside this AWS Organization AND the role the
      // monitor actually publishes as.
      //
      // That role is DevOpsAgentReadOnly, NOT the *-agent instance role. The
      // bootstrap sets AWS_PROFILE=devops-readonly whenever READONLY_ROLE_ARN is
      // present, so the whole piagent workload -- agent, monitor, CLI -- assumes
      // it, and the sns:Publish grant is on that role's pi-coms-extensions
      // policy. The dist bucket above guards a different principal (the instance
      // role writing checkpoints), so its "*-agent" pattern is right there and
      // wrong here; copying it rejected every intended publisher.
      //
      // aws:PrincipalArn resolves an assumed-role session to the ROLE arn, never
      // the session arn, so matching sts::...:assumed-role/ would never fire.
      // ArnLike is the operator AWS recommends for ARNs.
      Condition = {
        StringEquals = { "aws:PrincipalOrgID" = var.org_id }
        ArnLike      = { "aws:PrincipalArn" = "arn:aws:iam::*:role/DevOpsAgentReadOnly" }
      }
    }]
  })
}

// The email subscription is deliberately NOT declared here. SNS requires the
// recipient to confirm it out of band, and a Terraform-declared subscription
// sits "pending confirmation" in state forever until they click -- which reads
// as drift on every plan. Subscribe once by hand:
//   aws sns subscribe --topic-arn <arn> --protocol email --notification-endpoint <address>

output "monitor_report_sns_topic_arn" {
  description = "SIO-1821: pass this to each spoke root's monitor_report_sns_topic_arn."
  value       = aws_sns_topic.monitor_reports.arn
}

// SIO-1745: superseded checkpoint bodies. Each changed checkpoint writes a new
// content-addressed object and the manifest names only the latest, so the old
// bodies are unreachable and would otherwise accumulate forever.
//
// Scoped to the checkpoint-db/ prefix, never a bare "state/": S3 lifecycle
// filters are literal prefixes with no wildcards, so a rule covering the
// bodies cannot be written as state/*/*/db/ -- and a bare state/ prefix would
// expire manifest.json too, leaving a spoke quiet for 30 days with a deleted
// pointer and unreachable bodies. The manifest is tiny and never expired.
resource "aws_s3_bucket_lifecycle_configuration" "dist_state" {
  bucket = aws_s3_bucket.dist.id
  rule {
    id     = "expire-superseded-checkpoint-dbs"
    status = "Enabled"
    filter {
      prefix = "checkpoint-db/"
    }
    expiration {
      days = 30
    }
    noncurrent_version_expiration {
      noncurrent_days = 7
    }
    abort_incomplete_multipart_upload {
      days_after_initiation = 7
    }
  }
}

resource "aws_s3_bucket_policy" "dist_org_read" {
  bucket = aws_s3_bucket.dist.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "OrgRead"
        Effect    = "Allow"
        Principal = "*"
        Action    = ["s3:GetObject", "s3:ListBucket"]
        Resource  = [aws_s3_bucket.dist.arn, "${aws_s3_bucket.dist.arn}/*"]
        Condition = { StringEquals = { "aws:PrincipalOrgID" = var.org_id } }
      },
      // SIO-1745: a spoke writes its monitor-state checkpoint CROSS-ACCOUNT
      // (spoke account -> this shared-services bucket), and cross-account
      // access needs BOTH the caller's IAM grant and a resource-based Allow
      // here. Without this the write fails with "no resource-based policy
      // allows the s3:PutObject action" even though the instance role permits
      // it. The Deny below still confines each spoke to its own prefix.
      {
        Sid       = "OrgWriteCheckpointState"
        Effect    = "Allow"
        Principal = "*"
        Action    = ["s3:PutObject"]
        Resource = [
          "${aws_s3_bucket.dist.arn}/state/*",
          "${aws_s3_bucket.dist.arn}/checkpoint-db/*",
        ]
        // aws:PrincipalArn evaluates to the ROLE arn for an assumed-role
        // session, never the sts::assumed-role session arn -- AWS docs: "For
        // IAM roles, the request context returns the ARN of the role" and "Do
        // not specify the assumed role session ARN as a value for this
        // condition key." ArnLike is the operator AWS recommends for ARNs.
        Condition = {
          StringEquals = { "aws:PrincipalOrgID" = var.org_id }
          ArnLike      = { "aws:PrincipalArn" = "arn:aws:iam::*:role/*-agent" }
        }
      }
    ]
  })
}

// The prd hub. Directory mode: per-principal tokens under /pi-coms/auth;
// fleet tokens ensure mints one per spoke here.
module "hub" {
  source = "../../modules/hub"

  coms_auth_token = var.coms_auth_token
  subnet_id       = var.hub_subnet_id
  private_ip      = var.hub_private_ip
  allowed_cidrs   = var.allowed_cidrs
  repo_url        = var.repo_url
  bundle_s3_uri   = "s3://${aws_s3_bucket.dist.bucket}/fleet"
  dist_bucket_arn = aws_s3_bucket.dist.arn
  auth_ssm_path   = "/pi-coms/auth"
  port            = 8787
}

// Adopt mode: this account already carries DevOpsAgentReadOnly for the incident
// analyzer. The role is imported into state and its trust policy gains one
// statement for the local instance role; the analyzer's statement and the
// attached analyzer policies are never touched (see modules/agent).
import {
  to = module.agent.aws_iam_role.devops_readonly[0]
  id = "DevOpsAgentReadOnly"
}

module "agent" {
  source = "../../modules/agent"

  hub_url                      = module.hub.hub_url
  coms_auth_token              = var.coms_auth_token
  repo_url                     = var.repo_url
  agent_name                   = var.agent_name
  coms_project                 = "pi-coms-prd"
  monitor_tz                   = "Europe/Amsterdam"
  monitor_daily_cron           = "15 8 * * *"
  monitor_report_sns_topic_arn = aws_sns_topic.monitor_reports.arn
  subnet_id                    = var.agent_subnet_id
  associate_public_ip          = false
  instance_type                = "t4g.small"
  pi_model                     = var.pi_model
  pi_provider                  = "amazon-bedrock"
  enable_bedrock               = true
  readonly_role                = true
  readonly_role_mode           = "adopt"
  readonly_external_id         = var.readonly_external_id
  bundle_s3_uri                = "s3://${aws_s3_bucket.dist.bucket}/fleet"
  dist_bucket_arn              = aws_s3_bucket.dist.arn
}

// Every 30 minutes each tagged host compares its bundle version against S3 and
// re-bootstraps on change; `just fleet rollout` triggers the same command now.
resource "aws_ssm_association" "fleet_update" {
  name             = "AWS-RunShellScript"
  association_name = "pi-coms-fleet-update"

  targets {
    key    = "tag:Project"
    values = ["pi-coms-net"]
  }

  schedule_expression = "rate(30 minutes)"

  parameters = {
    commands = "[ -x /usr/local/bin/pi-coms-update ] && /usr/local/bin/pi-coms-update || true"
  }
}

output "agent_name" {
  value = module.agent.agent_name
}

output "agent_instance_id" {
  value = module.agent.agent_instance_id
}

output "devops_readonly_role_arn" {
  value = module.agent.devops_readonly_role_arn
}

output "provider_keys_parameter_name" {
  value = module.agent.provider_keys_parameter_name
}

output "attach_to_agent" {
  value = module.agent.attach_to_agent
}

output "hub_url" {
  value = module.hub.hub_url
}

output "hub_instance_id" {
  value = module.hub.hub_instance_id
}

output "dist_bucket" {
  value = aws_s3_bucket.dist.bucket
}

output "attach_to_hub" {
  value = module.hub.attach_to_hub
}
