// shared/src/index.ts
export {
	type DataSourceContext,
	DataSourceContextSchema,
	type DataSourceResult,
	DataSourceResultSchema,
	type ExtractedEntities,
	ExtractedEntitiesSchema,
	type StreamEvent,
	StreamEventSchema,
	type ToolError,
	type ToolErrorCategory,
	ToolErrorCategorySchema,
	ToolErrorSchema,
	type ToolOutput,
	ToolOutputSchema,
	type ToolPlanStep,
	ToolPlanStepSchema,
} from "./agent-state.ts";
export {
	type BootstrapLogger,
	type BootstrapTransportResult,
	createMcpApplication,
	type McpApplication,
	type McpApplicationOptions,
} from "./bootstrap.ts";
export { type AgentConfig, AgentConfigSchema, type ServerConfig, ServerConfigSchema } from "./config.ts";
export {
	type CapellaConfig,
	CapellaConfigSchema,
	DATA_SOURCE_IDS,
	type DataSourceId,
	type ElasticDeploymentConfig,
	ElasticDeploymentConfigSchema,
	type KafkaProviderConfig,
	KafkaProviderConfigSchema,
	type KonnectConfig,
	KonnectConfigSchema,
} from "./datasource.ts";
export {
	buildEcsOptions,
	createFormattedDestination,
	createMcpLogger,
	type EcsLoggerConfig,
	formatLogLine,
	getChildLogger,
	measureOperation,
} from "./logger.ts";
export { initTelemetry, shutdownTelemetry, type TelemetryConfig } from "./telemetry/telemetry.ts";
export {
	type ConnectionContext,
	createSessionContext,
	detectClient,
	generateSessionId,
	getCurrentClientInfo,
	getCurrentSession,
	getCurrentSessionId,
	getCurrentTrace,
	getRunTreeUtils,
	getTraceable,
	initializeTracing,
	isTracingActive,
	resetTracing,
	runWithSession,
	type SessionContext,
	type ToolTraceOptions,
	type TracingOptions,
	traceConnection,
	traceToolCall,
	traceToolExecution,
	withExtractedContext,
	withNestedTrace,
	withTraceContextMiddleware,
} from "./tracing/index.ts";
