// deploy/accounts/eu-shared-services-dev/backend.tf (generated by just fleet render, SIO-1653)
// Bucket, region and profile come from backend.hcl (gitignored, same command):
//   terraform init -backend-config=backend.hcl
// The state bucket is created once per environment by `just fleet backend-init <env>`.
terraform {
  backend "s3" {
    key          = "accounts/eu-shared-services-dev.tfstate"
    use_lockfile = true
    encrypt      = true
  }
}
